
const line = {
    'color': '256',
    'start': [0, 0, 0],
    'end': [0, 0, 0],
    'layer': '0',
}

const point = {
    'color': '256',
    'layer': '0',
    'point': [0, 0, 0],
}

const text = {
    'color': '256',
    'layer': '0',

}


const DXFHEADERS = [{'$ACADMAINTVER': {group: '70',
    description: 'Maintenance version number (should be ignored), '}},
  {'$ACADVER': {group: '1',
    description: 'The AutoCAD drawing database version number:, AC1006 = R10, AC1009 = R11 and R12, AC1012 = R13, AC1014 = R14, AC1015 = AutoCAD 2000, AC1018 = AutoCAD 2004, AC1021 = AutoCAD 2007, AC1024 = AutoCAD 2010, AC1027 = AutoCAD 2013, AC1032 = AutoCAD 2018, '}},
  {'$ANGBASE': {group: '50', description: 'Angle 0 direction, '}},
  {'$ANGDIR': {group: '70',
    description: '1 = Clockwise angles, 0 = Counterclockwise angles, '}},
  {'$ATTMODE': {group: '70',
    description: 'Attribute visibility:, 0 = None, 1 = Normal, 2 = All, '}},
  {'$AUNITS': {group: '70', description: 'Units format for angles, '}},
  {'$AUPREC': {group: '70', description: 'Units precision for angles, '}},
  {'$CECOLOR': {group: '62',
    description: 'Current entity color number:, 0 = BYBLOCK; 256 = BYLAYER, '}},
  {'$CELTSCALE': {group: '40',
    description: 'Current entity linetype scale, '}},
  {'$CELTYPE': {group: '6',
    description: 'Entity linetype name, or BYBLOCK or BYLAYER, '}},
  {'$CELWEIGHT': {group: '370',
    description: 'Lineweight of new objects, '}},
  {'$CEPSNID': {group: '390',
    description: 'Plotstyle handle of new objects; if CEPSNTYPE is 3, then this value indicates the handle, '}},
  {'$CEPSNTYPE': {group: '380',
    description: 'Plot style type of new objects:, 0 = Plot style by layer, 1 = Plot style by block, 2 = Plot style by dictionary default, 3 = Plot style by object ID/handle, '}},
  {'$CHAMFERA': {group: '40', description: 'First chamfer distance, '}},
  {'$CHAMFERB': {group: '40', description: 'Second chamfer distance, '}},
  {'$CHAMFERC': {group: '40', description: 'Chamfer length, '}},
  {'$CHAMFERD': {group: '40', description: 'Chamfer angle, '}},
  {'$CLAYER': {group: '8', description: 'Current layer name, '}},
  {'$CMLJUST': {group: '70',
    description: 'Current multiline justification:, 0 = Top; 1 = Middle; 2 = Bottom, '}},
  {'$CMLSCALE': {group: '40', description: 'Current multiline scale, '}},
  {'$CMLSTYLE': {group: '2',
    description: 'Current multiline style name, '}},
  {'$CSHADOW': {group: '280',
    description: 'Shadow mode for a 3D object:, 0 = Casts and receives shadows, 1 = Casts shadows, 2 = Receives shadows, 3 = Ignores shadows, Note: Starting with AutoCAD 2016-based products, this variable is obsolete but still supported for backwards compatibility., '}},
  {'$DIMADEC': {group: '70',
    description: 'Number of precision places displayed in angular dimensions, '}},
  {'$DIMALT': {group: '70',
    description: 'Alternate unit dimensioning performed if nonzero, '}},
  {'$DIMALTD': {group: '70',
    description: 'Alternate unit decimal places, '}},
  {'$DIMALTF': {group: '40', description: 'Alternate unit scale factor, '}},
  {'$DIMALTRND': {group: '40',
    description: 'Determines rounding of alternate units, '}},
  {'$DIMALTTD': {group: '70',
    description: 'Number of decimal places for tolerance values of an alternate units dimension, '}},
  {'$DIMALTTZ': {group: '70',
    description: 'Controls suppression of zeros for alternate tolerance values:, 0 = Suppresses zero feet and precisely zero inches, 1 = Includes zero feet and precisely zero inches, 2 = Includes zero feet and suppresses zero inches, 3 = Includes zero inches and suppresses zero feet, To suppress leading or trailing zeros, add the following values to one of the preceding values:, 4 = Suppresses leading zeros, 8 = Suppresses trailing zeros, '}},
  {'$DIMALTU': {group: '70',
    description: 'Units format for alternate units of all dimension style family members except angular:, 1 = Scientific, 2 = Decimal, 3 = Engineering, 4 = Architectural (stacked), 5 = Fractional (stacked), 6 = Architectural, 7 = Fractional, 8 = Operating system defines the decimal separator and number grouping symbols, '}},
  {'$DIMALTZ': {group: '70',
    description: 'Controls suppression of zeros for alternate unit dimension values:, 0 = Suppresses zero feet and precisely zero inches, 1 = Includes zero feet and precisely zero inches, 2 = Includes zero feet and suppresses zero inches, 3 = Includes zero inches and suppresses zero feet, 4 = Suppresses leading zeros in decimal dimensions, 8 = Suppresses trailing zeros in decimal dimensions, 12 = Suppresses both leading and trailing zeros, '}},
  {'$DIMAPOST': {group: '1',
    description: 'Alternate dimensioning suffix, '}},
  {'$DIMASO': {group: '70',
    description: '1 = Create associative dimensioning, 0 = Draw individual entities, Note: Obsolete; see $DIMASSOC., '}},
  {'$DIMASSOC': {group: '280',
    description: 'Controls the associativity of dimension objects, 0 = Creates exploded dimensions; there is no association between elements of the dimension, and the lines, arcs, arrowheads, and text of a dimension are drawn as separate objects, 1 = Creates non-associative dimension objects; the elements of the dimension are formed into a single object, and if the definition point on the object moves, then the dimension value is updated, 2 = Creates associative dimension objects; the elements of the dimension are formed into a single object and one or more definition points of the dimension are coupled with association points on geometric objects, '}},
  {'$DIMASZ': {group: '40', description: 'Dimensioning arrow size, '}},
  {'$DIMATFIT': {group: '70',
    description: 'Controls dimension text and arrow placement when space is not sufficient to place both within the extension lines:, 0 = Places both text and arrows outside extension lines, 1 = Moves arrows first, then text, 2 = Moves text first, then arrows, 3 = Moves either text or arrows, whichever fits best, AutoCAD adds a leader to moved dimension text when DIMTMOVE is set to 1, '}},
  {'$DIMAUNIT': {group: '70',
    description: "Angle format for angular dimensions:, 0 = Decimal degrees, 1 = Degrees/minutes/seconds;, 2 = Gradians, 3 = Radians, 4 = Surveyor's units, "}},
  {'$DIMAZIN': {group: '70',
    description: 'Controls suppression of zeros for angular dimensions:, 0 = Displays all leading and trailing zeros, 1 = Suppresses leading zeros in decimal dimensions, 2 = Suppresses trailing zeros in decimal dimensions, 3 = Suppresses leading and trailing zeros, '}},
  {'$DIMBLK': {group: '1', description: 'Arrow block name, '}},
  {'$DIMBLK1': {group: '1', description: 'First arrow block name, '}},
  {'$DIMBLK2': {group: '1', description: 'Second arrow block name, '}},
  {'$DIMCEN': {group: '40', description: 'Size of center mark/lines, '}},
  {'$DIMCLRD': {group: '70',
    description: 'Dimension line color:, range is 0 = BYBLOCK; 256 = BYLAYER, '}},
  {'$DIMCLRE': {group: '70',
    description: 'Dimension extension line color:, range is 0 = BYBLOCK; 256 = BYLAYER, '}},
  {'$DIMCLRT': {group: '70',
    description: 'Dimension text color:, range is 0 = BYBLOCK; 256 = BYLAYER, '}},
  {'$DIMDEC': {group: '70',
    description: 'Number of decimal places for the tolerance values of a primary units dimension, '}},
  {'$DIMDLE': {group: '40', description: 'Dimension line extension, '}},
  {'$DIMDLI': {group: '40', description: 'Dimension line increment, '}},
  {'$DIMDSEP': {group: '70',
    description: 'Single-character decimal separator used when creating dimensions whose unit format is decimal, '}},
  {'$DIMEXE': {group: '40', description: 'Extension line extension, '}},
  {'$DIMEXO': {group: '40', description: 'Extension line offset, '}},
  {'$DIMFAC': {group: '40',
    description: 'Scale factor used to calculate the height of text for dimension fractions and tolerances. AutoCAD multiplies DIMTXT by DIMTFAC to set the fractional or tolerance text height., '}},
  {'$DIMGAP': {group: '40', description: 'Dimension line gap, '}},
  {'$DIMJUST': {group: '70',
    description: 'Horizontal dimension text position:, 0 = Above dimension line and center-justified between extension lines, 1 = Above dimension line and next to first extension line, 2 = Above dimension line and next to second extension line, 3 = Above and center-justified to first extension line, 4 = Above and center-justified to second extension line, '}},
  {'$DIMLDRBLK': {group: '1',
    description: 'Arrow block name for leaders, '}},
  {'$DIMLFAC': {group: '40',
    description: 'Linear measurements scale factor, '}},
  {'$DIMLIM': {group: '70',
    description: 'Dimension limits generated if nonzero, '}},
  {'$DIMLUNIT': {group: '70',
    description: 'Sets units for all dimension types except Angular:, 1 = Scientific, 2 = Decimal, 3 = Engineering, 4 = Architectural, 5 = Fractional, 6 = Operating system, '}},
  {'$DIMLWD': {group: '70',
    description: 'Dimension line lineweight:, -3 = Standard, -2 = ByLayer, -1 = ByBlock, 0-211 = an integer representing 100th of mm, '}},
  {'$DIMLWE': {group: '70',
    description: 'Extension line lineweight:, -3 = Standard, -2 = ByLayer, -1 = ByBlock, 0-211 = an integer representing 100th of mm, '}},
  {'$DIMPOST': {group: '1', description: 'General dimensioning suffix, '}},
  {'$DIMRND': {group: '40',
    description: 'Rounding value for dimension distances, '}},
  {'$DIMSAH': {group: '70',
    description: 'Use separate arrow blocks if nonzero, '}},
  {'$DIMSCALE': {group: '40',
    description: 'Overall dimensioning scale factor, '}},
  {'$DIMSD1': {group: '70',
    description: 'Suppression of first extension line:, 0 = Not suppressed, 1 = Suppressed, '}},
  {'$DIMSD2': {group: '70',
    description: 'Suppression of second extension line:, 0 = Not suppressed, 1 = Suppressed, '}},
  {'$DIMSE1': {group: '70',
    description: 'First extension line suppressed if nonzero, '}},
  {'$DIMSE2': {group: '70',
    description: 'Second extension line suppressed if nonzero, '}},
  {'$DIMSHO': {group: '70',
    description: '1 = Recompute dimensions while dragging, 0 = Drag original image, '}},
  {'$DIMSOXD': {group: '70',
    description: 'Suppress outside-extensions dimension lines if nonzero, '}},
  {'$DIMSTYLE': {group: '2', description: 'Dimension style name, '}},
  {'$DIMTAD': {group: '70',
    description: 'Text above dimension line if nonzero, '}},
  {'$DIMTDEC': {group: '70',
    description: 'Number of decimal places to display the tolerance values, '}},
  {'$DIMTFAC': {group: '40',
    description: 'Dimension tolerance display scale factor, '}},
  {'$DIMTIH': {group: '70',
    description: 'Text inside horizontal if nonzero, '}},
  {'$DIMTIX': {group: '70',
    description: 'Force text inside extensions if nonzero, '}},
  {'$DIMTM': {group: '40', description: 'Minus tolerance, '}},
  {'$DIMTMOVE': {group: '70',
    description: 'Dimension text movement rules:, 0 = Moves the dimension line with dimension text, 1 = Adds a leader when dimension text is moved, 2 = Allows text to be moved freely without a leader, '}},
  {'$DIMTOFL': {group: '70',
    description: 'If text is outside the extension lines, dimension lines are forced between the extension lines if nonzero, '}},
  {'$DIMTOH': {group: '70',
    description: 'Text outside horizontal if nonzero, '}},
  {'$DIMTOL': {group: '70',
    description: 'Dimension tolerances generated if nonzero, '}},
  {'$DIMTOLJ': {group: '70',
    description: 'Vertical justification for tolerance values:, 0 = Top, 1 = Middle, 2 = Bottom, '}},
  {'$DIMTP': {group: '40', description: 'Plus tolerance, '}},
  {'$DIMTSZ': {group: '40',
    description: 'Dimensioning tick size:, 0 = Draws arrowheads, >0 = Draws oblique strokes instead of arrowheads, '}},
  {'$DIMTVP': {group: '40', description: 'Text vertical position, '}},
  {'$DIMTXSTY': {group: '7', description: 'Dimension text style, '}},
  {'$DIMTXT': {group: '40', description: 'Dimensioning text height, '}},
  {'$DIMTZIN': {group: '70',
    description: 'Controls suppression of zeros for tolerance values:, 0 = Suppresses zero feet and precisely zero inches, 1 = Includes zero feet and precisely zero inches, 2 = Includes zero feet and suppresses zero inches, 3 = Includes zero inches and suppresses zero feet, 4 = Suppresses leading zeros in decimal dimensions, 8 = Suppresses trailing zeros in decimal dimensions, 12 = Suppresses both leading and trailing zeros, '}},
  {'$DIMUPT': {group: '70',
    description: 'Cursor functionality for user-positioned text:, 0 = Controls only the dimension line location, 1 = Controls the text position as well as the dimension line location, '}},
  {'$DIMZIN': {group: '70',
    description: 'Controls suppression of zeros for primary unit values:, 0 = Suppresses zero feet and precisely zero inches, 1 = Includes zero feet and precisely zero inches, 2 = Includes zero feet and suppresses zero inches, 3 = Includes zero inches and suppresses zero feet, 4 = Suppresses leading zeros in decimal dimensions, 8 = Suppresses trailing zeros in decimal dimensions, 12 = Suppresses both leading and trailing zeros, '}},
  {'$DISPSILH': {group: '70',
    description: 'Controls the display of silhouette curves of body objects in Wireframe mode:, 0 = Off, 1 = On, '}},
  {'$DRAGVS': {group: '349',
    description: 'Hard-pointer ID to visual style while creating 3D solid primitives. The default value is NULL, '}},
  {'$DWGCODEPAGE': {group: '3',
    description: 'Drawing code page; set to the system code page when a new drawing is created, but not otherwise maintained by AutoCAD, '}},
  {'$ELEVATION': {group: '40',
    description: 'Current elevation set by ELEV command, '}},
  {'$ENDCAPS': {group: '280',
    description: 'Lineweight endcaps setting for new objects:, 0 = None, 1 = Round, 2 = Angle, 3 = Square, '}},
  {'$EXTMAX': {group: '10, 20, 30',
    description: 'X, Y, and Z drawing extents upper-right corner (in WCS), '}},
  {'$EXTMIN': {group: '10, 20, 30',
    description: 'X, Y, and Z drawing extents lower-left corner (in WCS), '}},
  {'$EXTNAMES': {group: '290',
    description: 'Controls symbol table naming:, 0 = AutoCAD Release 14 compatibility. Limits names to 31 characters in length. Names can include the letters A to Z, the numerals 0 to 9, and the special characters dollar sign ($), underscore (_), and hyphen (-)., 1 = AutoCAD 2000. Names can be up to 255 characters in length, and can include the letters A to Z, the numerals 0 to 9, spaces, and any special characters not used for other purposes by Microsoft Windows and AutoCAD, '}},
  {'$FILLETRAD': {group: '40', description: 'Fillet radius, '}},
  {'$FILLMODE': {group: '70', description: 'Fill mode on if nonzero, '}},
  {'$FINGERPRINTGUID': {group: '2',
    description: 'Set at creation time, uniquely identifies a particular drawing, '}},
  {'$HALOGAP': {group: '280',
    description: 'Specifies a gap to be displayed where an object is hidden by another object; the value is specified as a percent of one unit and is independent of the zoom level. A haloed line is shortened at the point where it is hidden when HIDE or the Hidden option of SHADEMODE is used, '}},
  {'$HANDSEED': {group: '5', description: 'Next available handle, '}},
  {'$HIDETEXT': {group: '290',
    description: 'Specifies HIDETEXT system variable:, 0 = HIDE ignores text objects when producing the hidden view, 1 = HIDE does not ignore text objects, '}},
  {'$HYPERLINKBASE': {group: '1',
    description: 'Path for all relative hyperlinks in the drawing. If null, the drawing path is used, '}},
  {'$INDEXCTL': {group: '280',
    description: 'Controls whether layer and spatial indexes are created and saved in drawing files:, 0 = No indexes are created, 1 = Layer index is created, 2 = Spatial index is created, 3 = Layer and spatial indexes are created, '}},
  {'$INSBASE': {group: '10, 20, 30',
    description: 'Insertion base set by BASE command (in WCS), '}},
  {'$INSUNITS': {group: '70',
    description: 'Default drawing units for AutoCAD DesignCenter blocks:, 0 = Unitless, 1 = Inches, 2 = Feet, 3 = Miles, 4 = Millimeters, 5 = Centimeters, 6 = Meters, 7 = Kilometers, 8 = Microinches, 9 = Mils, 10 = Yards, 11 = Angstroms, 12 = Nanometers, 13 = Microns, 14 = Decimeters, 15 = Decameters, 16 = Hectometers, 17 = Gigameters, 18 = Astronomical units, 19 = Light years, 20 = Parsecs, 21 = US Survey Feet, 22 = US Survey Inch, 23 = US Survey Yard, 24 = US Survey Mile, '}},
  {'$INTERFERECOLOR': {group: '62',
    description: 'Represents the ACI color index of the "interference objects" created during the INTERFERE command. Default value is 1, '}},
  {'$INTERFEREOBJVS': {group: '345',
    description: 'Hard-pointer ID to the visual style for interference objects. Default visual style is Conceptual., '}},
  {'$INTERFEREVPVS': {group: '346',
    description: 'Hard-pointer ID to the visual style for the viewport during interference checking. Default visual style is 3d Wireframe., '}},
  {'$INTERSECTIONCOLOR': {group: '70',
    description: 'Specifies the entity color of intersection polylines:, Values 1-255 designate an AutoCAD color index (ACI), 0 = Color BYBLOCK, 256 = Color BYLAYER, 257 = Color BYENTITY, '}},
  {'$INTERSECTIONDISPLAY': {group: '290',
    description: 'Specifies the display of intersection polylines:, 0 = Turns off the display of intersection polylines, 1 = Turns on the display of intersection polylines, '}},
  {'$JOINSTYLE': {group: '280',
    description: 'Lineweight joint setting for new objects:, 0=None, 1= Round, 2 = Angle, 3 = Flat, '}},
  {'$LIMCHECK': {group: '70',
    description: 'Nonzero if limits checking is on, '}},
  {'$LIMMAX': {group: '10, 20',
    description: 'XY drawing limits upper-right corner (in WCS), '}},
  {'$LIMMIN': {group: '10, 20',
    description: 'XY drawing limits lower-left corner (in WCS), '}},
  {'$LTSCALE': {group: '40', description: 'Global linetype scale, '}},
  {'$LUNITS': {group: '70',
    description: 'Units format for coordinates and distances, '}},
  {'$LUPREC': {group: '70',
    description: 'Units precision for coordinates and distances, '}},
  {'$LWDISPLAY': {group: '290',
    description: 'Controls the display of lineweights on the Model or Layout tab:, 0 = Lineweight is not displayed, 1 = Lineweight is displayed, '}},
  {'$MAXACTVP': {group: '70',
    description: 'Sets maximum number of viewports to be regenerated, '}},
  {'$MEASUREMENT': {group: '70',
    description: 'Sets drawing units:, 0 = English, 1 = Metric, '}},
  {'$MENU': {group: '1', description: 'Name of menu file, '}},
  {'$MIRRTEXT': {group: '70', description: 'Mirror text if nonzero, '}},
  {'$OBSCOLOR': {group: '70',
    description: 'Specifies the color of obscured lines. An obscured line is a hidden line made visible by changing its color and linetype and is visible only when the HIDE or SHADEMODE command is used. The OBSCUREDCOLOR setting is visible only if the OBSCUREDLTYPE is turned ON by setting it to a value other than 0., 0 and 256 = Entity color, 1-255 = An AutoCAD color index (ACI), '}},
  {'$OBSLTYPE': {group: '280',
    description: 'Specifies the linetype of obscured lines. Obscured linetypes are independent of zoom level, unlike standard object linetypes. Value 0 turns off display of obscured lines and is the default. Linetype values are defined as follows:, 0 = Off, 1 = Solid, 2 = Dashed, 3 = Dotted, 4 = Short Dash, 5 = Medium Dash, 6 = Long Dash, 7 = Double Short Dash, 8 = Double Medium Dash, 9 = Double Long Dash, 10 = Medium Long Dash, 11 = Sparse Dot, '}},
  {'$ORTHOMODE': {group: '70', description: 'Ortho mode on if nonzero, '}},
  {'$PDMODE': {group: '70', description: 'Point display mode, '}},
  {'$PDSIZE': {group: '40', description: 'Point display size, '}},
  {'$PELEVATION': {group: '40',
    description: 'Current paper space elevation, '}},
  {'$PEXTMAX': {group: '10, 20, 30',
    description: 'Maximum X, Y, and Z extents for paper space, '}},
  {'$PEXTMIN': {group: '10, 20, 30',
    description: 'Minimum X, Y, and Z extents for paper space, '}},
  {'$PINSBASE': {group: '10, 20, 30',
    description: 'Paper space insertion base point, '}},
  {'$PLIMCHECK': {group: '70',
    description: 'Limits checking in paper space when nonzero, '}},
  {'$PLIMMAX': {group: '10, 20',
    description: 'Maximum X and Y limits in paper space, '}},
  {'$PLIMMIN': {group: '10, 20',
    description: 'Minimum X and Y limits in paper space, '}},
  {'$PLINEGEN': {group: '70',
    description: 'Governs the generation of linetype patterns around the vertices of a 2D polyline:, 1 = Linetype is generated in a continuous pattern around vertices of the polyline, 0 = Each segment of the polyline starts and ends with a dash, '}},
  {'$PLINEWID': {group: '40', description: 'Default polyline width, '}},
  {'$PROJECTNAME': {group: '1',
    description: 'Assigns a project name to the current drawing. Used when an external reference or image is not found on its original path. The project name points to a section in the registry that can contain one or more search paths for each project name defined. Project names and their search directories are created from the Files tab of the Options dialog box, '}},
  {'$PROXYGRAPHICS': {group: '70',
    description: 'Controls the saving of proxy object images, '}},
  {'$PSLTSCALE': {group: '70',
    description: 'Controls paper space linetype scaling:, 1 = No special linetype scaling, 0 = Viewport scaling governs linetype scaling, '}},
  {'$PSTYLEMODE': {group: '290',
    description: 'Indicates whether the current drawing is in a Color-Dependent or Named Plot Style mode:, 0 = Uses named plot style tables in the current drawing, 1 = Uses color-dependent plot style tables in the current drawing, '}},
  {'$PSVPSCALE': {group: '40',
    description: 'View scale factor for new viewports:, 0 = Scaled to fit, >0 = Scale factor (a positive real value), '}},
  {'$PUCSBASE': {group: '2',
    description: 'Name of the UCS that defines the origin and orientation of orthographic UCS settings (paper space only), '}},
  {'$PUCSNAME': {group: '2',
    description: 'Current paper space UCS name, '}},
  {'$PUCSORG': {group: '10, 20, 30',
    description: 'Current paper space UCS origin, '}},
  {'$PUCSORGBACK': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing paper space UCS to BACK when PUCSBASE is set to WORLD, '}},
  {'$PUCSORGBOTTOM': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing paper space UCS to BOTTOM when PUCSBASE is set to WORLD, '}},
  {'$PUCSORGFRONT': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing paper space UCS to FRONT when PUCSBASE is set to WORLD, '}},
  {'$PUCSORGLEFT': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing paper space UCS to LEFT when PUCSBASE is set to WORLD, '}},
  {'$PUCSORGRIGHT': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing paper space UCS to RIGHT when PUCSBASE is set to WORLD, '}},
  {'$PUCSORGTOP': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing paper space UCS to TOP when PUCSBASE is set to WORLD, '}},
  {'$PUCSORTHOREF': {group: '2',
    description: 'If paper space UCS is orthographic (PUCSORTHOVIEW not equal to 0), this is the name of the UCS that the orthographic UCS is relative to. If blank, UCS is relative to WORLD, '}},
  {'$PUCSORTHOVIEW': {group: '70',
    description: 'Orthographic view type of paper space UCS:, 0 = UCS is not orthographic, 1 = Top, 2 = Bottom, 3 = Front, 4 = Back, 5 = Left, 6 = Right, '}},
  {'$PUCSXDIR': {group: '10, 20, 30',
    description: 'Current paper space UCS X axis, '}},
  {'$PUCSYDIR': {group: '10, 20, 30',
    description: 'Current paper space UCS Y axis, '}},
  {'$QTEXTMODE': {group: '70',
    description: 'Quick Text mode on if nonzero, '}},
  {'$REGENMODE': {group: '70',
    description: 'REGENAUTO mode on if nonzero, '}},
  {'$SHADEDGE': {group: '70',
    description: 'Controls the shading of edges:, 0 = Faces shaded, edges not highlighted, 1 = Faces shaded, edges highlighted in black, 2 = Faces not filled, edges in entity color, 3 = Faces in entity color, edges in black, '}},
  {'$SHADEDIF': {group: '70',
    description: 'Percent ambient/diffuse light; range 1-100; default 70, '}},
  {'$SHADOWPLANELOCATION': {group: '40',
    description: 'Location of the ground shadow plane. This is a Z axis ordinate., '}},
  {'$SKETCHINC': {group: '40', description: 'Sketch record increment, '}},
  {'$SKPOLY': {group: '70',
    description: 'Determines the object type created by the SKETCH command:, 0 = Generates lines, 1 = Generates polylines, 2 = Generates splines, '}},
  {'$SORTENTS': {group: '280',
    description: 'Controls the object sorting methods; accessible from the Options dialog box User Preferences tab. SORTENTS uses the following bitcodes:, 0 = Disables SORTENTS, 1 = Sorts for object selection, 2 = Sorts for object snap, 4 = Sorts for redraws; obsolete, 8 = Sorts for MSLIDE command slide creation; obsolete, 16 = Sorts for REGEN commands, 32 = Sorts for plotting, 64 = Sorts for PostScript output; obsolete, '}},
  {'$SPLINESEGS': {group: '70',
    description: 'Number of line segments per spline patch, '}},
  {'$SPLINETYPE': {group: '70',
    description: 'Spline curve type for PEDIT Spline, '}},
  {'$SURFTAB1': {group: '70',
    description: 'Number of mesh tabulations in first direction, '}},
  {'$SURFTAB2': {group: '70',
    description: 'Number of mesh tabulations in second direction, '}},
  {'$SURFTYPE': {group: '70',
    description: 'Surface type for PEDIT Smooth, '}},
  {'$SURFU': {group: '70',
    description: 'Surface density (for PEDIT Smooth) in M direction, '}},
  {'$SURFV': {group: '70',
    description: 'Surface density (for PEDIT Smooth) in N direction, '}},
  {'$TDCREATE': {group: '40',
    description: 'Local date/time of drawing creation (see Special Handling of Date/Time Variables), '}},
  {'$TDINDWG': {group: '40',
    description: 'Cumulative editing time for this drawing (see Special Handling of Date/Time Variables), '}},
  {'$TDUCREATE': {group: '40',
    description: 'Universal date/time the drawing was created (see Special Handling of Date/Time Variables), '}},
  {'$TDUPDATE': {group: '40',
    description: 'Local date/time of last drawing update (see Special Handling of Date/Time Variables), '}},
  {'$TDUSRTIMER': {group: '40', description: 'User-elapsed timer, '}},
  {'$TDUUPDATE': {group: '40',
    description: 'Universal date/time of the last update/save (see Special Handling of Date/Time Variables), '}},
  {'$TEXTSIZE': {group: '40', description: 'Default text height, '}},
  {'$TEXTSTYLE': {group: '7', description: 'Current text style name, '}},
  {'$THICKNESS': {group: '40',
    description: 'Current thickness set by ELEV command, '}},
  {'$TILEMODE': {group: '70',
    description: '1 for previous release compatibility mode; 0 otherwise, '}},
  {'$TRACEWID': {group: '40', description: 'Default trace width, '}},
  {'$TREEDEPTH': {group: '70',
    description: 'Specifies the maximum depth of the spatial index, '}},
  {'$UCSBASE': {group: '2',
    description: 'Name of the UCS that defines the origin and orientation of orthographic UCS settings, '}},
  {'$UCSNAME': {group: '2', description: 'Name of current UCS, '}},
  {'$UCSORG': {group: '10, 20, 30',
    description: 'Origin of current UCS (in WCS), '}},
  {'$UCSORGBACK': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing model space UCS to BACK when UCSBASE is set to WORLD, '}},
  {'$UCSORGBOTTOM': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing model space UCS to BOTTOM when UCSBASE is set to WORLD, '}},
  {'$UCSORGFRONT': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing model space UCS to FRONT when UCSBASE is set to WORLD, '}},
  {'$UCSORGLEFT': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing model space UCS to LEFT when UCSBASE is set to WORLD, '}},
  {'$UCSORGRIGHT': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing model space UCS to RIGHT when UCSBASE is set to WORLD, '}},
  {'$UCSORGTOP': {group: '10, 20, 30',
    description: 'Point which becomes the new UCS origin after changing model space UCS to TOP when UCSBASE is set to WORLD, '}},
  {'$UCSORTHOREF': {group: '2',
    description: 'If model space UCS is orthographic (UCSORTHOVIEW not equal to 0), this is the name of the UCS that the orthographic UCS is relative to. If blank, UCS is relative to WORLD, '}},
  {'$UCSORTHOVIEW': {group: '70',
    description: 'Orthographic view type of model space UCS:, 0 = UCS is not orthographic, 1 = Top, 2 = Bottom, 3 = Front, 4 = Back, 5 = Left, 6 = Right, '}},
  {'$UCSXDIR': {group: '10, 20, 30',
    description: 'Direction of the current UCS X axis (in WCS), '}},
  {'$UCSYDIR': {group: '10, 20, 30',
    description: 'Direction of the current UCS Y axis (in WCS), '}},
  {'$UNITMODE': {group: '70',
    description: "Low bit set = Display fractions, feet-and-inches, and surveyor's angles in input format, "}},
  {'$USERI1 - 5': {group: '70',
    description: 'Five integer variables intended for use by third-party developers, '}},
  {'$USERR1 - 5': {group: '40',
    description: 'Five real variables intended for use by third-party developers, '}},
  {'$USRTIMER': {group: '70',
    description: 'Controls the user timer for the drawing:, 0 = Timer off, 1 = Timer on, '}},
  {'$VERSIONGUID': {group: '2',
    description: 'Uniquely identifies a particular version of a drawing. Updated when the drawing is modified, '}},
  {'$VISRETAIN': {group: '70',
    description: "Controls the properties of xref-dependent layers:, 0 = Don't retain xref-dependent visibility settings, 1 = Retain xref-dependent visibility settings, "}},
  {'$WORLDVIEW': {group: '70',
    description: "Determines whether input for the DVIEW and VPOINT command evaluated as relative to the WCS or current UCS:, 0 = Don't change UCS, 1 = Set UCS to WCS during DVIEW/VPOINT, "}},
  {'$XCLIPFRAME': {group: '290',
    description: 'Controls the visibility of xref clipping boundaries:, 0 = Clipping boundary is not visible, 1 = Clipping boundary is visible, '}},
  {'$XEDIT': {group: '290',
    description: "Controls whether the current drawing can be edited in-place when being referenced by another drawing:, 0 = Can't use in-place reference editing, 1 = Can use in-place reference editing, "}}]



const DXFCLASSES = []
const DXFTABLES = []
const DXFBLOCKS = []
const DXFENTITIES = []
const DXFOBJECTS = []
const DXFTUMBNAILIMAGES = []

